name: Build
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        java: [ 16 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - name: Caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle.kts', 'gradle.properties', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Set Git Identity
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"

      - name: Clean Paperweight Cache
        run: ./gradlew cleanCache -Dpaperweight.debug=true

      - name: Apply CloudPlane Patches
        run: ./gradlew applyPatches -Dpaperweight.debug=true

      - name: Build Paperclip Jar
        run: ./gradlew createReobfPaperclipJar -Dpaperweight.debug=true

      - name: Upload Paperclip Jar
        uses: actions/upload-artifact@v2
        with:
          name: CloudPlane-Paperclip-JDK${{ matrix.java }}
          path: build/libs

  notify:
    runs-on: ubuntu-20.04
    if: always()

    needs: [ build ]
    steps:
      - name: Send Webhook
        run: |
          git clone https://github.com/Encode42/discord-workflows-webhook.git webhook
          bash webhook/send.sh ${{ needs.build.result }} ${{ secrets.WEBHOOK_URL }}
        shell: bash
